create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  last_name text not null,
  first_name text not null,
  phone_masked text not null,
  tier text not null check (tier in ('GOD', 'KING', 'BOSS', 'STAR', 'FAN')),
  gift_done boolean not null default false,
  gift_date date null,
  has_loan boolean not null default false,
  note text not null default '',
  gift_type text not null default '',
  delivered_by text not null default ''
);

create index if not exists clients_tier_idx on public.clients (tier);
create index if not exists clients_gift_done_idx on public.clients (gift_done);

grant usage on schema public to service_role;
grant select, insert, update on public.clients to service_role;
grant usage, select on sequence public.clients_id_seq to service_role;
